FROM cfx/registry:dev

MAINTAINER FooTearth "footearth@gmail.com"

WORKDIR /root/cfx.registry

# update
# RUN apt-get update && \
#     apt-get upgrade -y && \
#     apt-get autoremove -y

ENTRYPOINT [ "/bin/bash", "-lc" ]
CMD [ "yarn start" ]
